<?php
function mvp_render_settings() {
    if (isset($_POST['mvp_id_nonce']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['mvp_id_nonce'])), 'save_mvp_id')) {
        $tracking_id = isset($_POST['mvp_tracking_id']) ? sanitize_text_field(wp_unslash($_POST['mvp_tracking_id'])) : '';
        update_option('mvp_tracking_id', $tracking_id);
        echo '<div class="updated"><p>' . esc_html__('Tracking ID saved!', 'mvp-link-tracker-and-analytics') . '</p></div>';
    }
    $current = esc_attr(get_option('mvp_tracking_id', ''));
    echo '<div class="wrap"><h1>' . esc_html__('⚙️ MVP Settings', 'mvp-link-tracker-and-analytics') . '</h1>';
    echo '<form method="post">';
    echo '<table class="form-table"><tr><th scope="row"><label for="mvp_tracking_id">' . esc_html__('Your MVP Tracking ID (WT.mc_id)', 'mvp-link-tracker-and-analytics') . '</label></th>';
echo '<td><input type="text" id="mvp_tracking_id" name="mvp_tracking_id" value="' . esc_attr($current) . '" class="regular-text" required></td></tr></table>';
    // Nonce output is safe as it's generated by WordPress. If you ever echo wp_create_nonce() directly, wrap with esc_attr().
    wp_nonce_field('save_mvp_id', 'mvp_id_nonce');
    echo '<p class="submit"><input type="submit" class="button-primary" value="' . esc_attr__('Save Changes', 'mvp-link-tracker-and-analytics') . '" /></p>';
    echo '</form>';
    // Consent section
    $consent = get_option('mvp_consent_given', false);
    if (!$consent && isset($_POST['mvp_consent_nonce']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['mvp_consent_nonce'])), 'give_mvp_consent')) {
        update_option('mvp_consent_given', 1);
        $consent = 1;
        echo '<div class="updated"><p>' . esc_html__('Consent granted! Plugin is now active.', 'mvp-link-tracker-and-analytics') . '</p></div>';
    }
    // Export config
    if (isset($_POST['mvp_export_config_nonce']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['mvp_export_config_nonce'])), 'mvp_export_config')) {
        $config = [
            'mvp_tracking_id' => get_option('mvp_tracking_id', ''),
            'mvp_consent_given' => get_option('mvp_consent_given', false)
        ];
        header('Content-Type: application/json');
        header('Content-Disposition: attachment; filename="mvp-plugin-config.json"');
        // Direct output for download, intentionally not escaped
        echo json_encode($config, JSON_PRETTY_PRINT);
        exit;
    }
    // Import config
    if (isset($_POST['mvp_import_config_nonce']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['mvp_import_config_nonce'])), 'mvp_import_config') && isset($_FILES['mvp_config_file']['tmp_name']) && is_uploaded_file($_FILES['mvp_config_file']['tmp_name'])) {
        $tmp_name = sanitize_text_field(wp_unslash($_FILES['mvp_config_file']['tmp_name']));
        $json = file_get_contents($tmp_name);
        $config = json_decode($json, true);
        if (is_array($config)) {
            if (isset($config['mvp_tracking_id'])) update_option('mvp_tracking_id', sanitize_text_field($config['mvp_tracking_id']));
            if (isset($config['mvp_consent_given'])) update_option('mvp_consent_given', $config['mvp_consent_given'] ? 1 : 0);
            echo '<div class="updated"><p>' . esc_html__('Config imported successfully!', 'mvp-link-tracker-and-analytics') . '</p></div>';
        } else {
            echo '<div class="error"><p>' . esc_html__('Invalid config file.', 'mvp-link-tracker-and-analytics') . '</p></div>';
        }
    }
    if (!$consent) {
        echo '<hr><form method="post"><h2>Consent Required</h2><p>This plugin only works after you grant consent for link tracking. No personal data is stored.</p>';
        wp_nonce_field('give_mvp_consent', 'mvp_consent_nonce');
        echo '<p class="submit"><input type="submit" class="button-primary" value="Grant Consent & Activate Plugin"></p></form>';
    } else {
        echo '<hr><p><strong>Consent granted.</strong> Plugin is active.</p>';
    }
    // Export/Import buttons
    echo '<hr><h2>Export/Import Config</h2>';
    echo '<form method="post"><input type="hidden" name="mvp_export_config_nonce" value="' . esc_attr( wp_create_nonce('mvp_export_config') ) . '"><input type="submit" class="button-secondary" value="Export Config"></form>';
    echo '<form method="post" enctype="multipart/form-data" style="margin-top:10px"><input type="file" name="mvp_config_file" accept="application/json" required> ';
    wp_nonce_field('mvp_import_config', 'mvp_import_config_nonce');
    echo '<input type="submit" class="button-secondary" value="Import Config"></form>';
    echo '</div>';
}
